### ISSUE TITLE
Error building pyFVS

### ISSUE THREAD

**Issue by d-diaz** [tharen/PyFVS#13]
I tried following this repository's [readme_cmake.txt](https://github.com/tharen/PyFVS/blob/master/bin/readme_cmake.txt) instructions for configuring all variants for a release build, then building one variant at a time (Example 2):
```
cmake .. -G"MinGW Makefiles" -DRELEASE=1 -DWITH_PYMOD=ON`
...
mingw32-make wcc
```
The command runs for a good while, but then errors out with this message:
```
Scanning dependencies of target wcc
mingw32-make[3]: *** No rule to make target 'wcc/pyfvswcc', needed by 'wcc/CMakeFiles/wcc'.  Stop.
CMakeFiles\Makefile2:6272: recipe for target 'wcc/CMakeFiles/wcc.dir/all' failed
mingw32-make[2]: *** [wcc/CMakeFiles/wcc.dir/all] Error 2
CMakeFiles\Makefile2:6279: recipe for target 'wcc/CMakeFiles/wcc.dir/rule' failed
mingw32-make[1]: *** [wcc/CMakeFiles/wcc.dir/rule] Error 2
Makefile:2113: recipe for target 'wcc' failed
mingw32-make: *** [wcc] Error 2
```

I tried with both `-DWITH_PYMOD=ON` and `-DWITH_PYEXT=ON`, which appears to be the more recent option in CMakeLists.txt and got the same message.

**Comment by tharen** [comment]
A suffix was added to the Python extension target in CMakeLists.txt, but this was not reflected in the variant target list. I will push a fix to dev and master.

Executing a build with the 'install' target or the 'all' target (default) is not affected. This is my usual build scenario since I am only using a couple variants.
